config/routes.rb
Factory::Application.routes.draw do
	
	devise_for :users

	resources :accounts
	resources :imports
  	resources :item_specs
	resources :items do
		collection do
			get 'display'
		end
	end
	resources :specs
	resources :categories
	resources :tests
#	resources :users
	
	match 'item_specs/:id/cancel' => 'item_specs#cancel', :as => :cancel_item_spec
	match 'item_specs/:id/copy' => 'item_specs#copy', :as => :copy_item_spec
	match 'test/:id/instructions' => 'tests#instructions'
	match 'item_specs/:id/notes' => 'item_specs#notes', :as => :notes

	root :to => 'main#welcome'
	
  # Sample of regular route:
  #   match 'products/:id' => 'catalog#view'
  # Keep in mind you can assign values other than :controller and :action

  # Sample of named route:
  #   match 'products/:id/purchase' => 'catalog#purchase', :as => :purchase
  # This route can be invoked with purchase_url(:id => product.id)

 
  # Sample resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end

end

app/models/item_spec.rb
class ItemSpec < ActiveRecord::Base
	belongs_to :item
	belongs_to :spec
	belongs_to :test

	validates :item_id, :spec_id, :presence => true


	before_save :default_values
	
	def self.by_status(item)
		ItemSpec.includes(:spec => :category).where(:item_id => item).order("categories.display_order, specs.display_order, eff_date DESC, version DESC")
	end
	
	def date_status
		current_item_spec = ItemSpec
			.where(["item_id = ? AND spec_id = ? AND eff_date <= ?", self.item_id, self.spec_id, Date.today] )
			.order('eff_date DESC, version DESC').first
		if current_item_spec		
			current_date = current_item_spec.eff_date
			current_version = current_item_spec.version	
			if self.canceled
				"canceled"
			elsif (self.eff_date > Date.today)
				"pending"
			elsif self.deleted
				"deleted"
			elsif (self.eff_date == current_date and self.version < current_version) or self.eff_date < current_date
				"past"
			else
				"current"
			end
		else
			if self.canceled
				"canceled"
			else
				"future"
			end
		end
	end

	def set_version
		self.version = ((self.last_version.nil? && 0) || self.last_version) + 1
	end
	
	def last_version
		unless ItemSpec.where(:item_id => self.item_id, :spec_id => self.spec_id).empty?
			ItemSpec.where(:item_id => self.item_id, :spec_id => self.spec_id).order('version DESC').first.version
		end
	end
	
	def set_eff_date
		if !self.eff_date
			self.eff_date = Date.today
		end
	end

	def set_editor(user)
		self.changed_by = user
	end

	def default_values
		self.eff_date ||= Time.now
		self.string_value ||= ""
		self.text_value ||= ""
	end

end

app/controllers/item_specs_controller.rb
class ItemSpecsController < ApplicationController

include ApplicationHelper
require 'will_paginate/array'
load_and_authorize_resource 
	
  def index
		@history = params[:history]
		@pending = params[:pending]
		@specs = Spec.order(:display_order)
		set_scope
  	if @item
	  	@new_item_spec = ItemSpec.new
			@title = "Specifications for Item"
			@item_specs = ItemSpec.by_status(@item_id).paginate(:page => params[:page], :per_page => 20)
			@index = @item_specs
			@items = Item.order(:code)
			@available_specs = @item.available_specs
			@span = 12
			@is_index_table = true
		else
			flash[:alert] = "There are no items yet - please add at least one"
			redirect_to items_path
		end
  end
	
	def edit
		@item_spec = ItemSpec.find(params[:id])
		@new_item_spec = @item_spec.dup
		@is_edit_form = true
		@title = "#{@new_item_spec.spec.name} Specification"
	end
	
	def create
		if params[:commit] != 'Cancel'		
			@new_item_spec = ItemSpec.new(params[:item_spec])
			@new_item_spec.set_eff_date
			@new_item_spec.set_version
			@new_item_spec.set_editor(current_user.email)
logger.debug "@new_item_spec: #{@new_item_spec.inspect}"
			if @new_item_spec.save!
				flash[:success] = "Item Spec added/changed"
				redirect_to item_specs_path :item_id => params[:item_spec][:item_id]
			else
				redirect_to item_specs_path :item_id => params[:item_spec][:item_id]
			end
		else
			redirect_to item_specs_path :item_id => params[:item_spec][:item_id]
		end
	end

	def destroy
		@item_spec = ItemSpec.find(params[:id])
		@delete_item_spec = @item_spec.dup
		@delete_item_spec.deleted = true
		@delete_item_spec.set_eff_date
		@delete_item_spec.set_version
		@delete_item_spec.set_editor(current_user.email)
		if @delete_item_spec.save
			flash[:success] = "Item Spec deleted"
			redirect_to item_specs_path :item_id => @item_spec.item_id
		else
			redirect_to item_specs_path :item_id => @item_spec.item_id
		end
	end

	def copy
		@item_spec = ItemSpec.find(params[:id])
	end

	def cancel
		@item_spec = ItemSpec.find(params[:id])
		@item_spec.canceled = true
		@item_spec.set_eff_date
		@item_spec.set_version
		if @item_spec.save
			flash[:success] = "Future Item Spec canceled"
			redirect_to item_specs_path :item_id => @item_spec.item_id
		else
			redirect_to item_specs_path :item_id => @item_spec.item_id
		end
	end

	def notes
		@item_spec = ItemSpec.find(params[:id])
		@is_edit_form = true
		@title = "Notes for #{@item_spec.item.code}"
	end
	
	def update
		@item_spec = ItemSpec.find(params[:id])
		if params[:commit] != 'Cancel'			
			if @item_spec.update_attributes(params[:item_spec])
				flash[:success] = "Notes updated"
			else
				flash[:error] = "Unable to update notes"
			end
		end
		redirect_to item_specs_path :item_id => @item_spec.item_id
  end

	def set_scope
		if params[:item] && !params[:item].blank?
			@item_id = params[:item]	
		elsif params.has_key?(:item_spec)
			@item_id = params[:item_spec][:item_id]
		else
			@item_id = get_item_id
		end

		@item = Item.exists?(@item_id) ? Item.find(@item_id) : nil

		cookies[:item_id] = @item_id		
		@history = (params[:include_history] && !params[:include_history].blank?) || (@history && !@history.blank?)
		@pending = (params[:include_pending] && !params[:include_pending].blank?) || (@pending && !@pending.blank?)
	end
end

app/helpers/item_specs_helper.rb
module ItemSpecsHelper
end

app/views/item_specs/_index.html.erb
<% if ((item_spec.date_status == 'past' || 
	item_spec.date_status == 'deleted') && @history) || 
	(item_spec.date_status == 'pending' && !@pending) ||
	(item_spec.date_status == 'canceled' && @pending) ||
	item_spec.date_status == 'current' %>
	
	<tr class="<%= item_spec.date_status %>">
		<% if item_spec.spec.category %>
			<td><%= item_spec.spec.category.code %></td>
		<% else %>
			<td></td>
		<% end %>
		<td><%= item_spec.spec.code %></td>			
		<td><%= item_spec.string_value %></td>
		<td><%= item_spec.text_value %>
		<td><%= item_spec.numeric_value %></td>
		<td><%= item_spec.usl %></td>
		<td><%= item_spec.lsl %></td>
		<td><%= item_spec.unit_of_measure %></td>
		
		<td><%= item_spec.test.code if item_spec.test %></td>
		<td><%= item_spec.eff_date %></td>
		
		<td><%= item_spec.date_status %></td>
		<td><%= item_spec.changed_by %></td>
		<td class="centered">
				<%= link_to "Edit", edit_item_spec_path(item_spec) %>
			<% if item_spec.date_status == 'current' %>
				<%= link_to "Delete",  item_spec, :method => :delete, :confirm => "Are you sure?" %>
				
			<% elsif item_spec.date_status == 'pending' %>
				<%= link_to "Cancel", cancel_item_spec_path(item_spec), :confirm => "Are you sure?" %>				
			<% end %>
			
			<%= link_to "Notes", notes_path(item_spec) %>
		</td>
	</tr>	
<% end %>

app/views/item_specs/_new.html.erb
<tr>
	<%= form_for(@new_item_spec) do |f| %>
		<td></td>
		<td><%= f.collection_select :spec_id, @available_specs, :id, :code, {:prompt => :true}, {:style => "width:100%;"} %></td>
		<td><%= f.text_field :string_value, :style => "width:80%;" %></td>
		<td><%= f.text_field :text_value, :style => "width:80%;" %>
		<td><%= f.text_field :numeric_value, :style => "width:80%;" %></td>
		<td><%= f.text_field :usl, :style => "width:80%;" %></td>
		<td><%= f.text_field :lsl, :style => "width:80%;" %></td>
		<td><%= f.text_field :unit_of_measure, :style => "width:80%;" %></td>		
		<td><%= f.collection_select :test_id, Test.all, :id, :code, {:prompt => :true}, {:style => "width:100%;"} %></td>
		<td><%= f.text_field :eff_date, :style => "width:80%;" %></td>
		<td></td>
		
		<td></td>
		<td class="centered"><%= f.submit "Add Definition" %></td>
		<%= f.hidden_field :item_id, :value => @item_id %>
	<% end %>
</tr>


app/views/item_specs/edit.html.erb
<% content_for :edit_form do %>

	<p>Item: <%= @new_item_spec.item.code %></p>
	<p>Spec: <%= @new_item_spec.spec.code %></p>
	

	<%= form_for(@new_item_spec) do |f| %>
		
			
		<%= f.hidden_field :item_id %>
		<%= f.hidden_field :spec_id %>
		<%= f.hidden_field :version %>
		<%= f.label "Text", :class => "field_label" %>
		<%= f.text_field :string_value, :size => 15 %>
		<%= f.label "Long Text", :class => "field_label" %>
		<%= f.text_area :text_value, :rows => 1, :cols => 15 %>
		<%= f.label "Value", :class => "field_label" %>
		<%= f.text_field :numeric_value, :class => "number_field" %>
		<%= f.label "USL", :class => "field_label" %>
		<%= f.text_field :usl, :class => "number_field" %>
		<%= f.label "LSL", :class => "field_label" %>
		<%= f.text_field :lsl, :class => "number_field" %>
		<%= f.label "UOM", :class => "field_label" %>
		<%= f.text_field :unit_of_measure, :size => 6 %>
		
		<%= f.label "Test", :class => "field_label" %>
		<%= f.collection_select :test_id, Test.order('code'), :id, :code, :prompt => true, :include_blank => true %>
			
		
		
		<%= f.label "Effective Date of Edit" %>
		<%= f.text_field :eff_date, :class => "date_field" %>
		<div class="actions">
			<%= f.submit "Update Item" %>
			<%= f.submit "Cancel" %>
		</div>
	<% end %>	
<% end %>	

app/views/item_specs/index.html.erb

<% content_for :controls do %>	

		<%= form_tag('item_specs', :method => :get, :class => "form-inline") do %>
			 
			<%= collection_select :item_spec, :item_id, @items, :id, :code, {:selected => @item_id}, {:onchange => "this.form.submit();" } %>

			<%= label_tag 'include_pending', :class => "checkbox" do %>
				<%= check_box_tag "include_pending", "pending", @pending, :type => "checkbox" %>
				Hide pending
			<% end %>

			<%= label_tag 'include_history', :class => "checkbox" do %>				
				<%= check_box_tag "include_history", "history", @history, :type => "checkbox" %>
				Show history
			<% end %>
				
			<%= submit_tag "Apply" %>
		<% end %>
	
<% end %>

<% content_for :thead do %>			
	<th style="width: 6em">Category</th>
	<th style="width: 10em">Spec</th>
	<th>Text</th>
	<th>Multi-Line Text</th>
	<th style="width: 6em">Value</th>
	<th style="width: 6em">USL</th>
	<th style="width: 6em">LSL</th>
	<th style="width: 4em">UOM</th>	
	<th style="width: 8em">Test</th>
	<th style="width: 6em">Eff Dt</th>	
	<th style="width: 6em">Status</th>
	<th style="width: 10em">Edited By</th>
	<th style="width: 12em"></th>
<% end %>
		
<% content_for :table do %>
	<%= render 'new' %>
	<%= render :partial => 'index', :collection => @item_specs, :as => :item_spec %>
<% end %>

app/views/item_specs/notes.html.erb
<% content_for :edit_form do %>

	<p>Item: <%= @item_spec.item.code %></p>
	<p>Spec: <%= @item_spec.spec.code %></p>
	
	<%= form_for(@item_spec) do |f| %>
		
		<%= f.label "Notes" %>
		<%= f.text_area :notes %>
		
		<div class="actions">
			<%= f.submit "Update Notes" %>
			<%= f.submit "Cancel" %>
		</div>
	<% end %>	
<% end %>	