config/routes.rb
Factory::Application.routes.draw do
	
	devise_for :users

	resources :accounts
	resources :imports
  	resources :item_specs
	resources :items do
		collection do
			get 'display'
		end
	end
	resources :specs
	resources :categories
	resources :tests
#	resources :users
	
	match 'item_specs/:id/cancel' => 'item_specs#cancel', :as => :cancel_item_spec
	match 'item_specs/:id/copy' => 'item_specs#copy', :as => :copy_item_spec
	match 'test/:id/instructions' => 'tests#instructions'
	match 'item_specs/:id/notes' => 'item_specs#notes', :as => :notes

	root :to => 'main#welcome'
	
  # Sample of regular route:
  #   match 'products/:id' => 'catalog#view'
  # Keep in mind you can assign values other than :controller and :action

  # Sample of named route:
  #   match 'products/:id/purchase' => 'catalog#purchase', :as => :purchase
  # This route can be invoked with purchase_url(:id => product.id)

 
  # Sample resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end

end

app/models/spec.rb
class Spec < ActiveRecord::Base
	validates :code, :presence => true, :uniqueness => {:scope => :account_id}
	has_many :item_specs
	has_many :items, :through => :item_specs
	belongs_to :category

	default_scope { where(:account_id => Account.current_id)}
	
	def self.filtered(filter)
		Spec.where('code LIKE ?', filter).order('code') | Spec.where('code NOT LIKE ?', filter).order('code')
	end
	
	def reorder(new_order)
		old = self.id ? self.display_order : 0
		old ||= 0
		new_order ||= 0
		if new_order < old
			self.display_order = new_order
			self.save
			Spec.where('display_order >= ? AND display_order <= ? AND id != ?', new_order, old, self.id).update_all("display_order = display_order + 1") 
		elsif new_order > old && old > 0
			self.display_order = new_order
			self.save
			Spec.where('display_order >= ? AND display_order <= ? AND id != ?', old, new_order, self.id).update_all("display_order = display_order - 1")
		elsif old == 0
			specs = Spec.where('display_order >= ?', new_order).update_all("display_order = display_order + 1")
		end
		if Spec.count > 0
			if old != new_order && old > 0 || Spec.minimum(:display_order) > 1
				i = 1
				specs = Spec.order('display_order')
				specs.each do |s|
					s.display_order = i
					s.save
					i += 1
				end
			end
		end
	end

end

app/controllers/specs_controller.rb
class SpecsController < ApplicationController
	load_and_authorize_resource
	before_filter :find_specs
	
  def index
		@title = "Specification Definitions"
		@spec = Spec.new()
		@is_index_table = true
		@span = 8
	end
	
	def new
		@spec = Spec.new()
	end
	
	def create
		if params[:commit] != 'Cancel'
			@spec = Spec.new(params[:spec])
			order = (params[:spec][:display_order]).to_i
			@spec.reorder(order)
			if @spec.save
				flash[:success] = "Definition added"
				redirect_to specs_path
			else
				flash[:error] = "Definition could not be added"
#TODO Add more descriptive error messages
				redirect_to specs_path
			end
		else
			redirect_to specs_path
		end
	end

  def edit
		@spec = Spec.find(params[:id])
		@is_edit_form = true
		@title = "Specification: #{@spec.name}"
  end
	
	def update
		if params[:commit] != 'Cancel'
			@spec = Spec.find(params[:id])
			order = (params[:spec][:display_order]).to_i
			@spec.reorder(order)
			if @spec.update_attributes(params[:spec])
				flash[:success] = "Definition updated"
				redirect_to specs_path
			else
				redirect_to specs_path
			end
		else
			redirect_to specs_path
		end
	end
	
	def find_specs
		@specs = Spec.where(:deleted => false).order("display_order").paginate(:page => params[:page], :per_page => 20)
		@index = @specs
	end

end

app/helpers/specs_helper.rb
module SpecsHelper

	def active_categories
		Category.where(:deleted => false)
	end
end

app/views/specs/_new.html.erb

	<%= form_for(@spec) do |f| %>
			
				<div>
					<td><%= f.collection_select :category_id, active_categories, :id, :code, :prompt => :true %></td>
					<td><%= f.text_field :code, :class => 'text_field' %></td>
					<td><%= f.text_field :name, :class => 'text_field' %></td>
					<td><%= f.text_field :label, :class => 'text_field' %></td>
					<td class="centered"><%= f.number_field :display_order, :class => 'number_field_short' %></td>
					<td class="centered"><%= f.submit "Add Definition" %></td>
				</div>
			
		<% end %>		

app/views/specs/edit.html.erb

<% content_for :edit_form do %>
	<%= form_for(@spec) do |f| %>

		<%=f.label :code %>
		<%= f.text_field :code %>				
		<%=f.label :name, "Definition Name" %>
		<%= f.text_field :name %>
		

		<%=f.label :category_id %>
		<%= f.collection_select :category_id, Category.active, :id, :code, {:include_blank => "Please select"} %>
		<%=f.label :label %>
		<%= f.text_field :label %>
		<%=f.label :display_order %>
		<%= f.number_field :display_order %>
		
		<div>
			<%= f.submit "Submit Changes" %>
			<%= f.submit "Cancel" %>
		</div>
			
	<% end %>
<% end %>		

app/views/specs/index.html.erb
<% content_for :thead do %>
	<tr>
		<th style="width: 20%">Category</th>
		<th style="width: 20%">Definition Code</th>
		<th style="width: 20%">Definition Name</th>
		<th style="width: 20%">Label</th>
		<th style="width: 10%" class="centered">Default Order</th>
		<th style="width: 10%"></th>
	</tr>
<% end %>
		
<% content_for :table do %>
	<tr>
		<%= render 'new' %>
	</tr>

	<% @specs.each do |s| %>
		<tr>
			<td><%= s.category_id && !s.category.deleted ? s.category.name : nil %></td>
			<td><%= s.code %></td>
			<td><%= s.name %></td>
			<td><%= s.label %></td>
			<td class="centered"><%= s.display_order %></td>
			<td class="centered"><%= link_to "Edit", edit_spec_path(s) %>
					<%= link_to "Delete", spec_path(s), :method => :delete, :confirm => "Are you sure?" %>
			</td>
		</tr>
	<% end %>
<% end %>