config/routes.rb
Factory::Application.routes.draw do
	
	devise_for :users

	resources :accounts
	resources :imports
  	resources :item_specs
	resources :items do
		collection do
			get 'display'
		end
	end
	resources :specs
	resources :categories
	resources :tests
#	resources :users
	
	match 'item_specs/:id/cancel' => 'item_specs#cancel', :as => :cancel_item_spec
	match 'item_specs/:id/copy' => 'item_specs#copy', :as => :copy_item_spec
	match 'test/:id/instructions' => 'tests#instructions'
	match 'item_specs/:id/notes' => 'item_specs#notes', :as => :notes

	root :to => 'main#welcome'
	
  # Sample of regular route:
  #   match 'products/:id' => 'catalog#view'
  # Keep in mind you can assign values other than :controller and :action

  # Sample of named route:
  #   match 'products/:id/purchase' => 'catalog#purchase', :as => :purchase
  # This route can be invoked with purchase_url(:id => product.id)

 
  # Sample resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end

end

app/models/item.rb
class Item < ActiveRecord::Base
	validates :code, :presence => true, :uniqueness => {:scope => :account_id} # validates uniqueness within an account
	has_many :item_specs
	has_many :specs, :through => :item_specs

	default_scope { where(:account_id => Account.current_id)}
		
	def self.filtered(filter)
		Item.where('code LIKE ?', filter).order('code') | Item.where('code NOT LIKE ?', filter).order('code')
	end

	def self.by_existence(id)
		@count = Item.count(:all)
		case @count
		when 0
			nil
		when 1
			Item.find(:first)			
		else
			if Item.exists?(id)
				Item.find(id)
			else
				Item.find(:first)				
			end	
		end	
	end

	def self.id_by_existence(id)
		if Item.by_existence(id).blank?
			0
		else
			Item.by_existence(id).id
		end
	end

	def available_specs
		sql_string_used_specs = "
			SELECT a.*
			FROM
				((
				SELECT spec_id, MAX(version) as ver
				FROM item_specs
				WHERE item_id = #{self.id}					
				GROUP BY spec_id) AS y
			INNER JOIN
				(
				SELECT *
				FROM item_specs
				WHERE item_id = #{self.id}
				AND deleted = false) AS z
			ON y.spec_id = z.spec_id
			AND y.ver = z.version)
			INNER JOIN
				(
				SELECT *
				FROM specs) AS a
			ON a.id = z.spec_id
			"

		@used_specs = Spec.find_by_sql(sql_string_used_specs)
		if @used_specs.empty?
			Spec.all
		else
			Spec.where('id NOT IN (?)', @used_specs)
		end

	end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
	include ApplicationHelper
	require 'will_paginate/array'
	before_filter :find_items
	load_and_authorize_resource 

  def index
		@title = "Items"
		@new_item = Item.new	
		@specs = Spec.all
		@is_index_table = true
		@span = 5
  end

  def edit
		@item = Item.find(params[:id])
		@title = "Edit Item #{@item.code}"
		@is_edit_form = true
  end

  def update
  	if params[:commit] != 'Cancel'
			@item = Item.find(params[:id])
			@history = params[:history]
			@future = params[:future]
			if @item.update_attributes(params[:item])
				flash[:success] = "Item updated"
			else
				flash[:error] = "Unable to update item"
			end
		end
		redirect_to items_path
  end

  def new
		@item = Item.new
  end

  def create
		@item = Item.new(params[:item])
		if @item.save
			flash[:success] = "Item added"
			cookies[:item_id] = @item.id
			redirect_to items_path
		else
			flash[:error] = "Item could not be added"
#TODO Add more descriptive error messages
			redirect_to items_path
		end
	end

  def destroy
		Item.find(params[:id]).destroy
		flash[:success] = "Item deleted"
		redirect_to items_path
  end
	
	def display		
		@content_id = "display"
		if params.has_key?(:item)
			@item = Item.find(params[:item][:id])
		elsif params.has_key?(:item_id)
			@item = Item.by_existence(params[:item_id])		
		else
			@item = Item.find(get_item_id)
		end
		if @item
			authorize! :display, @item
			cookies[:item_id] = @item.id
			@title = @item.code
			@item_specs = ItemSpec.joins(:spec => :category).where(:item_id => @item).order("categories.display_order")
			@categories = @item_specs.group_by{|is| is.spec.category}			
		end
		render :layout => 'display_layout'
	end
	
	def find_items
		@items = Item.where(:deleted => false).order('code').paginate(:page => params[:page], :per_page => 20)
		@index = @items
	end

end

app/helpers/item_helper.rb
module ItemHelper
end

app/views/items/_header.html.erb
<div class="navbar navbar-fixed-top navbar-inverse">
	<nav class="navbar-inner">	
		
		<div class="nav pull-left">		
			<%= form_tag('display', :method => :get) do %>
				<%= label_tag 'specifications_for', :style=>"margin-left:1em;margin-top:0;" do %>
					Specifications for
					<% if @item %>
						<%= collection_select :item, :id, @items, :id, :code, {:selected => @item.id}, {:onchange => "this.form.submit();"} %>
					<% else %>
						<p>(No items available yet)</p>
					<% end %>
				<% end %>
			<% end %>
		</div>
						
		<ul class="nav pull-right">
			<% if @item %>
				<li><%= link_to "Floor Display", display_items_path(:item_id => @item.id ) %></li>
			<% end %>		
			<li><%= link_to "Items", items_path %></li>
			<li><%= link_to "Spec Definitions", specs_path %></li>
			<li><%= link_to "Item Specifications", item_specs_path %></li>
			<li><%= link_to "Categories", categories_path %></li>
			<li><%= link_to "Tests", tests_path %></li>
			<li><%= link_to "Import Data", new_import_path %></li>
			<li><%= link_to "Sign Out", destroy_user_session_path, :method => :delete %></li>			
		</ul>						
	</nav>
</div>		
	

app/views/items/_new.html.erb

	<tr>
		<%= form_for(@new_item) do |f| %>		
			<td><%= f.text_field :code %></td>
			<td><%= f.text_field :name %></td>
			<td class="centered"><%= f.submit "Submit New Item" %></td>
		<% end %>		
	</tr>

app/views/items/display.html.erb

<%= render "header" %>

<div id="display-box">
	
	<table class="table table-bordered table-striped table-hover" id="display-table">
		<thead id="display-header">
			<tr>
				<th class="category-name">Category</th>
				<th>Specification</th>
				<th class="spec-header">Lower Limit</th>
				<th style="text-align:center;">Target</th>
				<th class="spec-header" style="text-align:right;">Upper Limit</th>
				<th style="text-align:center;">Notes</th>
			</tr>
		</thead>
		<% if @categories %>
			<% @categories.each do |category, item_specs| %>

				<% r = 0 %>
				<% for s in item_specs %>	
					<% r = r + 1 %>
				<% end %>
				
				<tbody>
					<% first_row = true %>										
					<% for s in item_specs %>	
						<% if s.date_status == "current" %>
							<tr>
								<% if first_row %>
									<% first_row = false %>
									<td rowspan="<%= r %>" class="category-name">
										<%= category.name if category %>
									</td>
								<% end %>

								<td class="spec-name"><%= s.spec.name %></td>

								<td class="spec-limit"><%= s.lsl ||= nil %></td>

								<td class="spec-value" style="text-align:center;">
									
									<% if s.numeric_value %>								
										<%= "#{s.numeric_value} #{s.unit_of_measure}" %>
									<% end %>

									<% if !s.string_value.empty? %>
										<%= s.string_value %>
									<% end %>

									<% if !s.text_value.empty? %>
										<%= s.text_value %>								
									<% end %>

								</td>

								<td class="spec-limit" style="text-align:right;"><%= s.usl ||= nil %></td>								

								<td class="right-margin"><%= simple_format(s.notes ||= "") %></td>
								
							</tr>										
						<% end %>	
					<% end %>
				</tbody>
			<% end %>
		<% end %>
	</table> <!--! end of table -->
	
</div>

app/views/items/edit.html.erb
<% content_for :edit_form do %>

	<%= form_for @item do |f| %>
		
		<%= f.label :name, "Code", :class => "field_label" %>
		<%= f.text_field :code, :class => "text_field" %>
		
		<%= f.label :name, "Name", :class => "field_label" %>
		<%= f.text_field :name, :class => "text_field" %>
	
		<div>
			<%= f.submit "Update" %>
			<%= f.submit "Cancel" %>
		</div>	

	<% end %>
		
<% end %>

app/views/items/index.html.erb
<% content_for :thead do %>
	<tr>
		<th style="width: 40%">Item Code</th>
		<th style="width: 40%">Name</th>
		<th style="width: 20%"></th>
	</tr>
<% end %>

<% content_for :table do %>
	<%= render 'new' %>
	<% @items.each do |i| %>
		<tr>
			<td><%= i.code %></td>
			<td><%= i.name %></td>
			<td class="centered"><%= link_to "Edit", edit_item_path(i), :class => 'link' %>
					<%= link_to "Delete", item_path(i), :method => :delete, :confirm => "Are you sure?" %></td>
		</tr>
	<% end %>
<% end %>