config/routes.rb
Factory::Application.routes.draw do
	
	devise_for :users

	resources :accounts
	resources :imports
  	resources :item_specs
	resources :items do
		collection do
			get 'display'
		end
	end
	resources :specs
	resources :categories
	resources :tests
#	resources :users
	
	match 'item_specs/:id/cancel' => 'item_specs#cancel', :as => :cancel_item_spec
	match 'item_specs/:id/copy' => 'item_specs#copy', :as => :copy_item_spec
	match 'test/:id/instructions' => 'tests#instructions'
	match 'item_specs/:id/notes' => 'item_specs#notes', :as => :notes

	root :to => 'main#welcome'
	
  # Sample of regular route:
  #   match 'products/:id' => 'catalog#view'
  # Keep in mind you can assign values other than :controller and :action

  # Sample of named route:
  #   match 'products/:id/purchase' => 'catalog#purchase', :as => :purchase
  # This route can be invoked with purchase_url(:id => product.id)

 
  # Sample resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end

end

app/views/layouts/_edit_layout.html.erb
<div class="form span4 offset4">

	<div class="page-header">
		<h3><%= @title %></h3>
	</div>

	<%= yield :edit_form %>

</div>

app/views/layouts/_header_layout.html.erb
<div class="navbar navbar-fixed-top navbar-inverse">
  <nav class="navbar-inner">
	
		<ul class="nav pull-left">				
			<li><%= image_tag "icons/factory_white.svg", :alt=>"Factory", :size=>"33x30", :id=>"factory" %></li>
			<li><%= link_to current_user.email %></li>	
			<li><%= link_to "Account", account_path(current_user.account) %></li>
			<li><%= link_to "Sign Out", destroy_user_session_path, :method => :delete %></li>
		</ul>

		
		<div class="span4 offset2">
			<%= render 'layouts/messages_layout' %>
		</div>
		

		<ul class="nav pull-right">
			<li><%= link_to "Floor Display", display_items_path(:item_id => @item_id ) %></li>		
			<li><%= link_to "Items", items_path %></li>
			<li><%= link_to "Spec Definitions", specs_path %></li>
			<li><%= link_to "Item Specifications", item_specs_path %></li>
			<li><%= link_to "Categories", categories_path %></li>
			<li><%= link_to "Tests", tests_path %></li>
			<li><%= link_to "Import Data", new_import_path %></li>			
		</ul>	
		
	</nav>
</div>

app/views/layouts/_index.html.erb
<div class="span<%= @span %>">
	<div class="row-fluid">	
		<h4 class="title"><%= @title %></h4>
		<div class="controls">
			<%= yield :controls %>
		</div>
		
		<% unless index.blank? %>
			<%= will_paginate index, :renderer => BootstrapPagination::Rails %>
		<% end %>

		<table class="table table-striped table-bordered table-condensed">
			<thead>
				<%= yield :thead %>
			</thead>
			<tbody>
				<%= yield :table %>
			</tbody>
		</table>

		<% unless index.blank? %>
			<%= will_paginate index, :renderer => BootstrapPagination::Rails %>
		<% end %>

	</div>
</div>

app/views/layouts/_index_layout.html.erb
<div class="span<%= @span %>">
	<div class="row-fluid">	
		<h4 class="title"><%= @title %></h4>
		<div class="controls">
			<%= yield :controls %>
		</div>
		
		<% unless index.blank? %>
			<%= will_paginate index, :renderer => BootstrapPagination::Rails %>
		<% end %>

		<table class="table table-striped table-bordered table-condensed">
			<thead>
				<%= yield :thead %>
			</thead>
			<tbody>
				<%= yield :table %>
			</tbody>
		</table>

		<% unless index.blank? %>
			<%= will_paginate index, :renderer => BootstrapPagination::Rails %>
		<% end %>

	</div>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |type, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert <%= twitterized_type(type)%>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{twitterized_type(type)}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_messages_layout.html.erb
<% flash.each do |type, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert <%= twitterized_type(type)%>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{twitterized_type(type)}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
	  <title><%= @title %></title>
	  <%= stylesheet_link_tag "application" %>
	  <%= javascript_include_tag "application" %>
	  <%= csrf_meta_tags %>
	</head>

	<% if user_signed_in? %>
		<body>
			<div class="content" id="<%= @content_id %>">

				<% if !@no_header %>					
			    <%= render 'layouts/header_layout' %>			    
		    <% end %>

				<div id="main" role="main">					
					<div class="container-fluid">
	        	<div class="row-fluid">
	        			        		
					   	<%= render :partial => 'layouts/index_layout', :object => @index, :as => :index if @is_index_table %>
					    					    
					    <%= render :partial => 'layouts/edit_layout' if @is_edit_form %>
					           	
	          	<%= yield %>
	          </div>
	        </div> <!--! end of .container --> 	       
	    	</div> <!--! end of #main -->		
			</div> <!--! end of content -->
		</body>

	<% else %>
		<body id="welcome">
			<div class="content">							
				<%= yield %>
			</div>	
		</body>			
	<% end %>

</html>

app/views/layouts/display_layout.html.erb
<!DOCTYPE html>
<html>
	<head>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
	  <title><%= @title %></title>
	  <%= stylesheet_link_tag "display" %>
	  <%= javascript_include_tag "application" %>
	  <%= csrf_meta_tags %>
	</head>
	
	<body>
		<div class="content" id="<%= @content_id %>">
			<div id="main" role="main">					
				<div class="container-fluid">
        	<div class="row-fluid">
        			        		
				   	<%= render :partial => 'layouts/index_layout', :object => @index, :as => :index if @is_index_table %>
				   
          	<%= yield %>
          </div>
        </div> <!--! end of .container --> 	       
    	</div> <!--! end of #main -->		
		</div> <!--! end of content -->
	</body>

</html>